data-loading {
  rawDataPath="data/ddtg/ddtg.csv"
  writePath="data/parquet-ddtg-tman-5/"
  objectIdIndex=0
  longitudeIndex=2
  latitudeIndex=3
  timeIndex=1
  dateFormat="yyyy-MM-dd HH:mm:ss"
  delimiter=","
  metricsPathExport="data/"
  wholeWorld = false
  maxResolution = 5
  alpha = 5
  beta = 5
}
