data-loading {
  rawDataPath="data/geolife/"
  writePath="data/parquet-geolife-vre/"
  objectIdIndex=0
  longitudeIndex=2
  latitudeIndex=1
  timeIndex=3
  dateFormat="yyyy-MM-dd HH:mm:ss"
  delimiter=","
  metricsPathExport="data/"
  hilbert {
      bits = 6
  }
  wholeWorld = false
  maxResolution = 16
  m = 5
  n = 5
}
