data-loading {
  rawDataPath="data/berlinmod/berlinmod.csv"
  writePath="data/parquet-berlinmod-vre-8/"
  objectIdIndex=0
  longitudeIndex=2
  latitudeIndex=3
  timeIndex=1
  dateFormat="yyyy-MM-dd HH:mm:ss.SSS"
  delimiter=","
  metricsPathExport="data/"
  hilbert {
      bits = 4
  }
  wholeWorld = false
  maxResolution = 8
  m = 5
  n = 5
}
