data-loading {
  rawDataPath="data/geolife/"
  writePath="data/parquet-geolife-frequet/"
  objectIdIndex=0
  longitudeIndex=2
  latitudeIndex=1
  timeIndex=3
  dateFormat="yyyy-MM-dd HH:mm:ss"
  delimiter=","
  metricsPathExport="data/"
  hilbert {
    bits = 6
;     minLon=-9.713331
;     minLat=45.001045
;     minTime=1443650401000
;     maxLon=-0.015736665
;     maxLat=50.7706
;     maxTime=1459461603000
  }
}
