data-loading {
  rawDataPath="data/geolife/"
  writePath="data/parquet-geolife-tman/"
  objectIdIndex=0
  longitudeIndex=2
  latitudeIndex=1
  timeIndex=3
  dateFormat="yyyy-MM-dd HH:mm:ss"
  delimiter=","
  metricsPathExport="data/"
  wholeWorld = false
  maxResolution = 16
  alpha = 5
  beta = 5
}
